name: 'Setup project'
description: 'Install dependencies and other project setup'
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      shell: bash
      run: uv python install ${{ env.PYTHON_VERSION }}
    - name: Install Dependencies
      shell: bash
      run: |
        uv sync
        echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=${{ github.workspace }}/.venv" >> $GITHUB_ENV
