import enum


class Attribute(str, enum.Enum):
    AIR_PRESSURE = "air pressure"
    AIR_TEMPERATURE = "air temperature"
    AIR_TEMPERATURE_MAX = "air temperature max"
    AIR_TEMPERATURE_MIN = "air temperature min"
    BATTERY_VOLTAGE = "battery voltage"
    BATTERY_LOW = "battery low"
    CLOUD_COVER = "cloud cover"
    CLOUD_COVER_HIGH = "cloud cover high"
    CLOUD_COVER_LOW = "cloud cover low"
    CLOUD_COVER_MEDIUM = "cloud cover medium"
    CO2 = "co2"
    CURRENT = "current"
    CURRENT_L1 = "current l1"
    CURRENT_L2 = "current l2"
    CURRENT_L3 = "current l3"
    ENERGY = "energy"
    HUMIDITY = "humidity"
    NOISE = "noise"
    POWER = "power"
    POWER_STATE = "power state"
    PRECIPITATION_AMOUNT = "precipitation amount"
    PRECIPITATION_AMOUNT_MAX = "precipitation amount max"
    PRECIPITATION_AMOUNT_MIN = "precipitation amount min"
    VOLTAGE = "voltage"
    VOLTAGE_L1 = "voltage l1"
    VOLTAGE_L2 = "voltage l2"
    VOLTAGE_L3 = "voltage l3"
